function weeklyLearningStats(){const learning=coachState();const since=addDays(today(),-6);const lessons=learning.history.filter(item=>item.date>=since);const practices=learning.practiceHistory.filter(item=>item.date>=since);return {lessons,practices,weak:learning.weakPoints||[]}}
function learningReportCard(){const stats=weeklyLearningStats();const weak=stats.weak.length?'<div class="small">建议重点：'+esc(stats.weak.join("、"))+'</div>':'<div class="small">暂时没有明显薄弱点，继续保持。</div>';return '<section class="card"><div class="row"><div><h2>本周 AI 学习报告</h2><div class="small">把学习变成可以持续改进的能力。</div></div><span class="tag">'+stats.lessons.length+' 课 · '+stats.practices.length+' 次练习</span></div><div class="followup-stats"><span class="tag green">课程完成 '+stats.lessons.length+'</span><span class="tag gold">练习完成 '+stats.practices.length+'</span><span class="tag">待加强 '+(stats.weak.length||0)+'</span></div><p class="muted">'+(stats.lessons.length>=5?'本周学习节奏很好，下一步重点是把方法用到真实工作中。':'保持每天一小步，本周完成 5 节课程即可形成稳定习惯。')+'</p>'+weak+'</section>'}
function practicalAdviceCard(){const active=state.tasks.filter(item=>!item.done).sort(order).slice(0,3);const advice=active.length?'你当前最值得优先推进的是：'+active.map(item=>item.title||item.text).join('、')+'。先完成最小下一步，再让 AI 帮你继续拆解。':'今天暂无明确待办，可以记录一件最想推进的事情。';return '<section class="card"><h2>AI 实用建议</h2><p class="muted">结合你的工作、生活、资产和备考记录，给出可以立即执行的小建议。</p><div class="answer-card">'+esc(advice)+'</div><div class="small">提示：涉及财务、健康或重要决策时，把 AI 建议当作参考，并核对原始信息。</div></section>'}
const dailyLearningCardV074=dailyLearningCard;
dailyLearningCard=function(){return dailyLearningCardV074()+learningReportCard()+practicalAdviceCard()}
render();
const renderV075=render;
render=function(){renderV075();const subtitle=document.querySelector(".top p");if(subtitle)subtitle.textContent="V0.7.5 · AI学习闭环版"}
render();
