function coachState(){const learning=lessonState();if(!Array.isArray(learning.practiceHistory))learning.practiceHistory=[];if(!Array.isArray(learning.weakPoints))learning.weakPoints=[];return learning}
function practicePrompt(){const lesson=currentLesson();return `请用自己的话回答：${lesson.practice}`}
function practiceCard(){const learning=coachState();const lesson=currentLesson();const todayPractice=learning.practiceHistory.find(item=>item.date===today()&&item.lessonIndex===(Number(learning.lessonIndex)||0));return `<section class="card"><div class="row"><div><h2>AI 练习教练</h2><div class="small">把今天学到的方法用到真实工作中，回答后会得到改进建议。</div></div><span class="tag ${todayPractice?"green":""}">${todayPractice?"今日已练习":"今日练习"}</span></div><h3>${esc(practicePrompt())}</h3><textarea id="coachAnswer" class="field" rows="4" placeholder="写下你的回答或实际例子"></textarea><div class="actions"><button class="btn" onclick="submitPractice()">${todayPractice?"重新练习":"提交练习"}</button><button class="btn secondary" onclick="showCoachProgress()">查看进步</button></div>${todayPractice?`<div class="answer-card"><b>上次反馈</b><div>${esc(todayPractice.feedback)}</div></div>`:""}${feedback.coach?`<div class="feedback">✓ ${esc(feedback.coach)}</div>`:""}</section>`}
function evaluatePractice(text){const answer=text.trim();if(answer.length<12)return "回答还比较简短。请补充具体目标、对象、时间或限制中的至少两项。";const checks=[{keys:["目标","想要","结果","完成"],tip:"目标已经比较清楚"},{keys:["时间","今天","明天","截止","周"],tip:"加入了时间信息"},{keys:["限制","不能","注意","预算","资料"],tip:"考虑到了限制条件"},{keys:["医院","客户","主任","设备科","任务","工作"],tip:"已经联系到真实工作场景"}];const matched=checks.filter(item=>item.keys.some(key=>answer.includes(key))).map(item=>item.tip);return matched.length>=2?`回答抓住了${matched.join("、")}。下一步可以把它改写成一个明确动作，并补充完成标准。`:`已经开始思考了。建议继续补充目标、时间和限制，让 AI 能据此给出更准确的方案。`}
function submitPractice(){const input=document.getElementById("coachAnswer");const text=input?.value.trim();if(!text){feedback.coach="请先写下你的回答";render();return}const learning=coachState();const index=Number(learning.lessonIndex)||0;const row={id:`practice-${Date.now()}`,date:today(),lessonIndex:index,answer:text,feedback:evaluatePractice(text)};learning.practiceHistory.unshift(row);learning.weakPoints=learning.weakPoints.filter(item=>item!=="提示词结构");if(text.length<12)learning.weakPoints.unshift("提示词结构");save();feedback.coach="练习已记录，建议根据反馈再改写一次";render()}
function showCoachProgress(){const learning=coachState();const practiced=learning.practiceHistory.length;const completed=learning.history.length;const weak=learning.weakPoints.length?learning.weakPoints.join("、"):"暂时没有明显薄弱点";feedback.coach=`已完成 ${completed} 节课程，完成 ${practiced} 次练习；需要加强：${weak}`;render()}
const dailyLearningCardV073=dailyLearningCard;
dailyLearningCard=function(){return dailyLearningCardV073()+practiceCard()}
render();
