const KEY="personalWorkbench";
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(date,n)=>{const d=new Date(date+"T12:00:00");d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const clean=v=>String(v||"").replace(/```[\s\S]*?```/g,"").replace(/^\s*(?:#{1,6}\s*|\d+[.)]\s*|[-*>]\s*)/gm,"").replace(/\*\*/g,"").trim();
const defaults=()=>({notes:[],finance:[],life:[],health:[],study:[],tasks:[],followups:[],radar:[],hospitals:[],opportunities:[],ai:{endpoint:"",auto:false},passkey:{enabled:false},backupVersion:1});
let state=(()=>{try{return {...defaults(),...JSON.parse(localStorage.getItem(KEY)||"{}")} }catch{return defaults()}})();
for(const k of ["tasks","followups","radar","hospitals","opportunities"]){if(!Array.isArray(state[k]))state[k]=[]}
let page="home",actions=[],feedback={},modal="",loading=false,answerText="";
const label={home:"\u9996\u9875",assistant:"AI\u52a9\u7406",tasks:"\u6267\u884c",radar:"\u672a\u6765\u96f7\u8fbe",customers:"\u5ba2\u6237/\u5546\u673a",settings:"\u8bbe\u7f6e"};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function render(){document.getElementById("app").innerHTML=`<div class="shell"><header class="top"><h1>\u4e2a\u4eba\u5de5\u4f5c\u53f0</h1><p>V0.6.1 路 \u5ba2\u6237\u5546\u673a\u81ea\u52a8\u5173\u8054\u7248</p></header><main class="content">${pageView()}</main><nav class="nav">${Object.entries(label).map(([id,name])=>`<button class="${page===id?"active":""}" onclick="go('${id}')">${name}</button>`).join("")}</nav></div>${modal}`}
function render(){document.getElementById("app").innerHTML=`<div class="shell"><header class="top"><h1>\u4e2a\u4eba\u5de5\u4f5c\u53f0</h1><p>V0.6.7 · \u8ddf\u8fdb\u590d\u76d8\u4e2d\u5fc3</p></header><main class="content">${pageView()}</main><nav class="nav">${Object.entries(label).map(([id,name])=>`<button class="${page===id?"active":""}" onclick="go('${id}')">${name}</button>`).join("")}</nav></div>${modal}`}
function go(next){page=next;modal="";render()}
function pageView(){return page==="assistant"?assistantView():page==="tasks"?tasksView():page==="radar"?radarView():page==="customers"?customersView():page==="settings"?settingsView():homeView()}
function order(a,b){const p={high:0,medium:1,low:2};return(p[a.priority]??1)-(p[b.priority]??1)||String(a.dueDate||"9999").localeCompare(String(b.dueDate||"9999"))}
function active(){return state.tasks.filter(x=>!x.done&&(!x.dueDate||x.dueDate<=addDays(today(),31))).sort(order)}
function homeView(){const list=active();return `<section class="card"><div class="row"><div><div class="small">\u672c\u6708\u91cd\u70b9</div><div class="metric">${list.length}</div><div>\u4ef6\u5f85\u63a8\u8fdb</div></div><button class="btn" onclick="go('assistant')">\u8bb0\u5f55\u4e00\u4ef6\u4e8b</button></div></section><section class="card"><div class="row"><h2>\u4eca\u5929\u6700\u91cd\u8981\u7684 3 \u4ef6\u4e8b</h2><button class="btn secondary" onclick="go('tasks')">\u6267\u884c\u4e2d\u5fc3</button></div>${list.slice(0,3).map(taskItem).join("")||'<div class="empty">\u4eca\u5929\u6ca1\u6709\u5f85\u529e</div>'}</section><section class="card"><h2>\u5de5\u4f5c\u53f0\u5206\u533a</h2><p class="muted">\u968f\u53e3\u8bb0\u3001\u8d22\u52a1\u3001\u751f\u6d3b\u3001\u5065\u5eb7\u3001\u5907\u8003\u548c\u8ba4\u8bc1\u6570\u636e\u7ee7\u7eed\u4fdd\u7559\u5728\u672c\u673a\u3002</p></section>`}
function assistantView(){return `<section class="card"><h2>AI业务助理</h2><p class="muted">记录一件事来拆分任务，也可以直接问医院、联系人、商机和跟进事项。</p><textarea id="note" class="field" rows="5" placeholder="例如：北医三院现在有哪些事？"></textarea><div class="quick-queries"><button class="btn tertiary" onclick="fillQuery('北医三院现在有哪些事？')">查北医三院</button><button class="btn tertiary" onclick="fillQuery('这个月哪些主任该联系？')">本月谁该联系</button><button class="btn tertiary" onclick="fillQuery('30天内最值得推进的商机有哪些？')">近30天商机</button></div><button class="btn block" onclick="askAI()" ${loading?"disabled":""}>${loading?"正在处理…":"提问 / 拆解任务"}</button>${answerText?`<section class="answer-card"><h3>业务查询结果</h3><div>${esc(answerText).replace(/\n/g,"<br>")}</div></section>`:""}${actions.map(actionCard).join("")}</section>`}
function fillQuery(value){const input=document.getElementById("note");if(input)input.value=value}
function actionCard(x,i){const id=x.id??i;return `<article class="card action-card"><div class="row"><span class="tag">\u4efb\u52a1 ${i+1}</span><span class="tag ${x.priority==="high"?"red":"gold"}">${x.priority==="high"?"\u9ad8\u4f18\u5148\u7ea7":"\u4e2d\u4f18\u5148\u7ea7"}</span></div><h3>${esc(x.title)}</h3><div class="action-line"><b>\u8981\u505a\u4ec0\u4e48</b><span>${esc(x.what)}</span></div><div class="action-line"><b>\u4e3a\u4ec0\u4e48\u73b0\u5728\u505a</b><span>${esc(x.why)}</span></div><div class="meta">${x.dueDate?`<span class="tag">\u622a\u6b62 ${esc(x.dueDate)}</span>`:""}${[x.hospital,x.department,x.contact,x.project].filter(Boolean).map(v=>`<span class="tag">${esc(v)}</span>`).join("")}</div><div class="actions"><button class="btn" onclick="addTask(${id})">\u52a0\u5165\u4eca\u65e5\u4efb\u52a1</button><button class="btn secondary" onclick="dateAction(${id},'follow')">\u52a0\u5165\u672c\u5468</button><button class="btn tertiary" onclick="dateAction(${id},'radar')">\u52a0\u5165\u672a\u6765\u96f7\u8fbe</button></div>${feedback[id]?`<div class="feedback">鉁?${esc(feedback[id])}</div>`:""}</article>`}
function fallback(note){const s=clean(note),has=s.includes("\u5149\u7ea4")||s.includes("\u91c7\u8d2d\u91cf");if(has)return [{title:"\u786e\u8ba4\u5149\u7ea4\u578b\u53f7\u548c\u9884\u8ba1\u6570\u91cf",what:"\u5411\u4e3b\u4efb\u786e\u8ba4\u4e0b\u6708\u5149\u7ea4\u578b\u53f7\u548c\u91c7\u8d2d\u6570\u91cf",why:"\u5148\u9501\u5b9a\u9700\u6c42\uff0c\u624d\u80fd\u51c6\u5907\u65b9\u6848\u3002",dueDate:today(),priority:"high",contact:"\u4e3b\u4efb"},{title:"\u786e\u8ba4\u8bbe\u5907\u79d1\u91c7\u8d2d\u6d41\u7a0b",what:"\u8054\u7cfb\u8bbe\u5907\u79d1\uff0c\u786e\u8ba4\u91c7\u8d2d\u8def\u5f84\u548c\u4e0b\u5355\u65f6\u95f4",why:"\u63d0\u524d\u786e\u8ba4\u6d41\u7a0b\uff0c\u907f\u514d\u5361\u5728\u5ba1\u6279\u5165\u53e3\u3002",dueDate:addDays(today(),3),priority:"high",department:"\u8bbe\u5907\u79d1"},{title:"\u51c6\u5907\u62a5\u4ef7\u548c\u5e93\u5b58\u65b9\u6848",what:"\u6839\u636e\u578b\u53f7\u548c\u6570\u91cf\u51c6\u5907\u62a5\u4ef7\u3001\u5e93\u5b58\u4e0e\u4ea4\u4ed8\u65b9\u6848",why:"\u63d0\u524d\u51c6\u5907\u53ef\u4ee5\u5feb\u901f\u54cd\u5e94\u91c7\u8d2d\u7a97\u53e3\u3002",dueDate:addDays(today(),7),priority:"medium",project:"\u5149\u7ea4\u91c7\u8d2d"},{title:"\u8bbe\u7f6e\u91c7\u8d2d\u524d\u518d\u6b21\u8ddf\u8fdb",what:"\u5728\u9884\u8ba1\u91c7\u8d2d\u524d 7 \u5929\u518d\u8054\u7cfb\u4e3b\u4efb",why:"\u5728\u5173\u952e\u8282\u70b9\u56de\u770b\uff0c\u907f\u514d\u610f\u5411\u9057\u6f0f\u3002",dueDate:addDays(today(),23),priority:"medium",project:"\u5149\u7ea4\u91c7\u8d2d",contact:"\u4e3b\u4efb"}];return [{title:`\u786e\u8ba4\uff1a${s.slice(0,22)}`,what:s,why:"\u5148\u628a\u8bb0\u5f55\u53d8\u6210\u660e\u786e\u52a8\u4f5c\u3002",dueDate:today(),priority:"high"}]}
function normalize(data){const raw=data.tasks||data.actions||data.items;if(!Array.isArray(raw))return[];return raw.slice(0,5).map((x,i)=>typeof x==="string"?{...fallback(x)[0],id:i}:{...x,id:i,title:/^(\u786e\u8ba4|\u51c6\u5907|\u8054\u7cfb|\u8bbe\u7f6e|\u6838\u5bf9|\u6574\u7406|\u63d0\u4ea4|\u5b89\u6392)/.test(clean(x.title||x.name))?clean(x.title||x.name):`\u63a8\u8fdb\uff1a${clean(x.title||x.name||x.what)}`,what:clean(x.what||x.action||x.next||x.title),why:clean(x.why||x.reason),dueDate:x.dueDate||x.deadline||addDays(today(),i?7:0),priority:["high","medium","low"].includes(x.priority)?x.priority:"medium",hospital:clean(x.hospital),department:clean(x.department),contact:clean(x.contact),project:clean(x.project)})}
function associate(note){const hay=clean(note).toLowerCase();const hospital=state.hospitals.find(x=>x.name&&hay.includes(x.name.toLowerCase()));const opportunity=state.opportunities.find(x=>(x.name&&hay.includes(x.name.toLowerCase()))||(x.type&&hay.includes(x.type.toLowerCase())&&(!hospital||x.hospital===hospital.name)));actions=actions.map(x=>({...x,hospital:x.hospital||hospital?.name||"",department:x.department||hospital?.department||"",contact:x.contact||hospital?.contact||"",project:x.project||opportunity?.name||""}));if(hospital){hospital.lastContact=today();save()}for(const x of actions){const row={...x,id:"linked-"+Date.now()+"-"+Math.random(),text:x.what,createdAt:today(),done:false,source:"ai"};const list=x.dueDate&&x.dueDate>today()?state.radar:state.tasks;if(!anyTask(row))list.unshift(row)}save()}
function fillQuery(value){const input=document.getElementById("note");if(!input)return;const buttons=Array.from(document.querySelectorAll(".quick-queries button"));const index=buttons.indexOf(window.event?.currentTarget);input.value=["\u5317\u533b\u4e09\u9662\u73b0\u5728\u6709\u54ea\u4e9b\u4e8b\uff1f","\u8fd9\u4e2a\u6708\u54ea\u4e9b\u4e3b\u4efb\u8be5\u8054\u7cfb\uff1f","30\u5929\u5185\u6700\u503c\u5f97\u63a8\u8fdb\u7684\u5546\u673a\u6709\u54ea\u4e9b\uff1f"][index]||value}
function isQuery(q){return /\u54ea\u4e9b\u4e8b|\u54ea\u4e9b\u4efb\u52a1|\u6709\u4ec0\u4e48\u4e8b|\u8c01\u8be5\u8054\u7cfb|\u8be5\u8054\u7cfb\u8c01|\u5546\u673a\u6709\u54ea\u4e9b|\u503c\u5f97\u63a8\u8fdb|\u4eca\u5929\u5148\u505a\u4ec0\u4e48|\u672c\u5468\u91cd\u70b9|\u672c\u6708\u91cd\u70b9|30\u5929/.test(q)||(q.includes("\u54ea\u4e9b")&&q.includes("\u8054\u7cfb"))||(q.includes("\u672c\u6708")&&q.includes("\u8054\u7cfb"))}
function localAnswer(q){const hospital=state.hospitals.find(item=>item.name&&q.includes(item.name));return hospital?`医院：${hospital.name}；联系人：${hospital.contact||"未录入"}；最近联系：${hospital.lastContact||"未记录"}`:"医院：未指定或客户库中未找到匹配"}
async function askAI(){const note=document.getElementById("note")?.value.trim();if(!note)return;const query=isQuery(note);answerText="";actions=query?[]:fallback(note).map((x,i)=>({...x,id:i}));loading=true;render();const endpointRaw=state.ai.endpoint||"",endpoint=endpointRaw.endsWith("/")?endpointRaw.slice(0,-1):endpointRaw;if(endpoint){try{const r=await fetch(endpoint+"/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:note,mode:query?"business_query":"task_extract",context:{today:today(),tasks:state.tasks,followups:state.followups,radar:state.radar,hospitals:state.hospitals,opportunities:state.opportunities}})});if(r.ok){const data=await r.json();if(query)answerText=clean(data.answer||data.response||data.text||"");else{const parsed=normalize(data);if(parsed.length)actions=parsed}}}catch{}}if(query&&!answerText)answerText=localAnswer(note);if(!query)associate(note);loading=false;render()}
function localAnswer(q){const h=state.hospitals.find(x=>x.name&&q.includes(x.name));const thirty=q.includes("30\u5929"),limit=addDays(today(),30);const opps=state.opportunities.filter(x=>(!h||x.hospital===h.name)&&(!thirty||!x.expectedDate||x.expectedDate<=limit));const tasks=state.tasks.filter(x=>!x.done&&(!h||x.hospital===h.name));const radar=state.radar.filter(x=>!x.done&&(!h||x.hospital===h.name));const contacts=state.hospitals.filter(x=>x.contact&&(!x.lastContact||x.lastContact<=addDays(today(),-30)));return [(h?"\u533b\u9662\uff1a"+h.name+"\uff1b\u79d1\u5ba4\uff1a"+(h.department||"\u672a\u5f55\u5165")+"\uff1b\u8054\u7cfb\u4eba\uff1a"+(h.contact||"\u672a\u5f55\u5165")+"\uff1b\u6700\u8fd1\u8054\u7cfb\uff1a"+(h.lastContact||"\u672a\u8bb0\u5f55"):"\u533b\u9662\uff1a\u672a\u6307\u5b9a\u6216\u5ba2\u6237\u5e93\u4e2d\u672a\u627e\u5230\u5339\u914d"),"\u672a\u5b8c\u6210\u4efb\u52a1\uff1a"+(tasks.map(x=>x.title||x.text).join("\uff1b")||"\u6682\u65e0"),"\u672a\u6765\u96f7\u8fbe\uff1a"+(radar.map(x=>x.title||x.text).join("\uff1b")||"\u6682\u65e0"),"\u76f8\u5173\u5546\u673a\uff1a"+(opps.map(x=>x.name+"\uff08"+(x.stage||"\u9636\u6bb5\u672a\u586b")+"\uff0c"+(x.next||"\u4e0b\u4e00\u6b65\u672a\u586b")+"\uff09").join("\uff1b")||"\u6682\u65e0"),"\u5f85\u8054\u7cfb\u8054\u7cfb\u4eba\uff1a"+(contacts.map(x=>(x.name||"")+ " "+x.contact+"\uff08"+(x.lastContact||"\u4ece\u672a\u8054\u7cfb")+"\uff09").join("\uff1b")||"\u6682\u65e0")].join("\n")}
function fp(x){return [x.what||x.text,x.title,x.hospital,x.department,x.contact,x.project].map(v=>clean(v).toLowerCase()).join("|")}
function anyTask(x){return [state.tasks,state.followups,state.radar].some(list=>list.some(y=>fp(x)===fp(y)))}
function addTask(id){const x=actions[id];if(!x)return;if(anyTask(x)){feedback[id]="\u4efb\u52a1\u5df2\u5b58\u5728\uff0c\u5df2\u907f\u514d\u91cd\u590d";render();return}state.tasks.unshift({...x,id:`task-${Date.now()}-${id}`,text:x.what,createdAt:today(),done:false,source:"ai"});save();feedback[id]="\u5df2\u52a0\u5165\u4eca\u65e5\u4efb\u52a1";render()}
function dateAction(id,type){const x=actions[id];if(!x)return;modal=`<div class="modal-backdrop"><section class="modal"><h3>${type==="follow"?"\u52a0\u5165\u672c\u5468":"\u52a0\u5165\u672a\u6765\u96f7\u8fbe"}</h3><p>${esc(x.what)}</p><input id="dateValue" class="field" type="date" value="${x.dueDate||addDays(today(),7)}" min="${today()}"><div class="modal-row"><button class="btn tertiary" onclick="closeModal()">\u53d6\u6d88</button><button class="btn" onclick="saveDate(${id},'${type}')">\u4fdd\u5b58</button></div></section></div>`;render()}
function saveDate(id,type){const date=document.getElementById("dateValue")?.value,x=actions[id];if(!date||!x)return;const row={...x,id:`${type}-${Date.now()}-${id}`,text:x.what,date,dueDate:date,createdAt:today(),done:false,source:"ai"};const list=type==="follow"?state.followups:state.radar;if(!anyTask(row))list.unshift(row);save();feedback[id]=anyTask(row)?"\u4efb\u52a1\u5df2\u5b58\u5728":"\u5df2\u4fdd\u5b58";modal="";render()}
function closeModal(){modal="";render()}
function taskItem(item){const title=item.title||item.text||"未命名任务";const details=[item.source?("来源："+(item.source==="ai"?"AI任务提炼":"跟进计划")):"",item.project?("项目："+item.project):"",item.hospital?("医院："+item.hospital):""].filter(Boolean).join(" · ");return `<div class="list-item"><div class="task-row ${item.done?"done":""}"><input type="checkbox" ${item.done?"checked":""} onchange="toggleTask(&quot;${esc(item.id)}&quot;)"><div><strong>${esc(title)}</strong><div class="small">${esc(item.what||item.text||"")}${item.dueDate?" · 截止 "+esc(item.dueDate):""}${item.done&&item.completedAt?" · 完成于 "+esc(item.completedAt):""}</div><div class="small">${esc(details)}</div></div><div><span class="tag ${item.done?"green":""}">${item.done?"已完成":item.priority==="high"?"高优先级":"中优先级"}</span>${item.done?`<button class="btn tertiary mini" onclick="removeTask(&quot;${esc(item.id)}&quot;)">删除</button>`:""}</div></div></div>`}
function tasksView(){return `<section class="card"><h2>AI\u6267\u884c\u4e2d\u5fc3</h2><p class="muted">\u4efb\u52a1\u4e0e\u539f\u6709\u4e1a\u52a1\u6570\u636e\u7ee7\u7eed\u5171\u5b58\u3002</p></section><section class="card"><h2>\u672a\u5b8c\u6210</h2>${state.tasks.filter(x=>!x.done).sort(order).map(taskItem).join("")||'<div class="empty">\u6682\u65e0\u5f85\u529e</div>'}</section><section class="card"><h2>\u5df2\u5b8c\u6210</h2>${state.tasks.filter(x=>x.done).map(taskItem).join("")||'<div class="empty">\u6682\u65e0\u5386\u53f2</div>'}</section>`}
function toggleTask(id){for(const list of [state.tasks,state.followups,state.radar]){const x=list.find(y=>y.id===id);if(x){x.done=!x.done;if(x.done)x.completedAt=today();else delete x.completedAt;break}}save();render()}
function removeTask(id){for(const list of [state.tasks,state.followups,state.radar]){const i=list.findIndex(x=>x.id===id);if(i>=0){list.splice(i,1);break}}save();render()}
function radarView(){const items=state.radar.filter(x=>!x.done).sort(radarOrder);const overdue=items.filter(x=>radarStatus(x)==="overdue");const todayItems=items.filter(x=>radarStatus(x)==="today");const upcoming=items.filter(x=>radarStatus(x)==="upcoming");return `<section class="card"><h2>\u667a\u80fd\u8ddf\u8fdb\u4e2d\u5fc3</h2><p class="muted">\u6309\u65e5\u671f\u68c0\u67e5\u533b\u9662\u3001\u8054\u7cfb\u4eba\u3001\u5546\u673a\u548c\u4e0b\u4e00\u6b65\u3002\u5df2\u5b8c\u6210\u4e8b\u9879\u4f1a\u81ea\u52a8\u79bb\u5f00\u91cd\u70b9\u3002</p><div class="followup-stats"><span class="tag red">\u5df2\u903e\u671f ${overdue.length}</span><span class="tag gold">\u4eca\u5929 ${todayItems.length}</span><span class="tag">\u672a\u6765\u8282\u70b9 ${upcoming.length}</span></div>${radarSection("\u5df2\u903e\u671f",overdue)}${radarSection("\u4eca\u5929\u8be5\u505a",todayItems)}${radarSection("\u672a\u6765\u8282\u70b9",upcoming)}${items.length?"":"<div class=\"empty\">\u672a\u6765\u96f7\u8fbe\u8fd8\u662f\u7a7a\u7684</div>"}</section>`}
function radarStatus(x){const date=x.dueDate||x.date||"9999-12-31";return date<today()?"overdue":date===today()?"today":"upcoming"}
function radarOrder(a,b){const rank={overdue:0,today:1,upcoming:2};return (rank[radarStatus(a)]-rank[radarStatus(b)])||order(a,b)}
function radarSection(title,items){if(!items.length)return "";return `<section class="followup-section"><h3>${title}<span class="small">${items.length} 椤?/span></h3>${items.map(radarItem).join("")}</section>`}
function radarSection(title,items){if(!items.length)return "";return `<section class="followup-section"><h3>${title}<span class="small">${items.length} 项</span></h3>${items.map(radarItem).join("")}</section>`}
function radarItem(item){const date=item.dueDate||item.date||"";const relation=[item.hospital,item.department,item.contact,item.project].filter(Boolean).join(" · ");return `<div class="list-item"><div class="task-row"><div><strong>${esc(item.title||item.text)}</strong><div class="small">${esc(item.what||item.text)}${date?` · 截止 ${esc(date)}`:""}</div><div class="small">${relation?esc(relation):"未关联客户或商机"}</div></div><div class="actions"><button class="btn mini" onclick="promoteRadar(&quot;${esc(item.id)}&quot;)">转为今日任务</button><button class="btn secondary mini" onclick="snoozeRadar(&quot;${esc(item.id)}&quot;,7)">延后7天</button><button class="btn tertiary mini" onclick="contactDone(&quot;${esc(item.id)}&quot;)">已联系</button></div></div></div>`}
function promoteRadar(id){const item=state.radar.find(candidate=>candidate.id===id);if(!item)return;if(!state.tasks.some(task=>!task.done&&fp(task)===fp(item))){state.tasks.unshift({...item,id:`task-${Date.now()}`,dueDate:today(),date:today(),bucket:"today"})}item.promotedAt=today();save();render()}
function snoozeRadar(id,days){const item=state.radar.find(candidate=>candidate.id===id);if(!item)return;const nextDate=addDays(today(),days);item.dueDate=nextDate;item.date=nextDate;item.snoozedAt=today();save();render()}
function contactDone(id){const item=state.radar.find(candidate=>candidate.id===id);if(!item)return;item.done=true;item.completedAt=today();const hospital=state.hospitals.find(candidate=>item.hospital&&candidate.name===item.hospital);if(hospital)hospital.lastContact=today();save();render()}
function editHospital(id){const h=state.hospitals.find(x=>x.id===id)||{id:"",name:"",department:"",contact:"",phone:"",lastContact:"",stage:"",note:""};modal=`<div class="modal-backdrop"><section class="modal"><h3>${id?"\u7f16\u8f91\u533b\u9662":"\u65b0\u589e\u533b\u9662"}</h3><input id="hn" class="field" placeholder="\u533b\u9662\u540d\u79f0" value="${esc(h.name)}"><input id="hd" class="field" placeholder="\u79d1\u5ba4" value="${esc(h.department)}"><input id="hc" class="field" placeholder="\u8054\u7cfb\u4eba" value="${esc(h.contact)}"><input id="hp" class="field" placeholder="\u8054\u7cfb\u65b9\u5f0f" value="${esc(h.phone)}"><input id="hl" class="field" type="date" value="${esc(h.lastContact)}"><input id="hs" class="field" placeholder="\u5173\u7cfb\u9636\u6bb5" value="${esc(h.stage)}"><textarea id="ht" class="field" placeholder="\u5907\u6ce8">${esc(h.note)}</textarea><div class="modal-row"><button class="btn tertiary" onclick="closeModal()">\u53d6\u6d88</button><button class="btn" onclick="saveHospital('${esc(id||"")}')">\u4fdd\u5b58</button></div></section></div>`;render()}
function saveHospital(id){const h={id:id||`h-${Date.now()}`,name:document.getElementById("hn").value.trim(),department:document.getElementById("hd").value.trim(),contact:document.getElementById("hc").value.trim(),phone:document.getElementById("hp").value.trim(),lastContact:document.getElementById("hl").value,stage:document.getElementById("hs").value.trim(),note:document.getElementById("ht").value.trim()};if(!h.name)return;const i=state.hospitals.findIndex(x=>x.id===h.id);if(i>=0)state.hospitals[i]=h;else state.hospitals.unshift(h);save();modal="";render()}
function editOpportunity(id){const o=state.opportunities.find(x=>x.id===id)||{id:"",type:"鑰楁潗",name:"",hospital:"",department:"",contact:"",stage:"",amount:"",expectedDate:"",next:""};modal=`<div class="modal-backdrop"><section class="modal"><h3>${id?"\u7f16\u8f91\u5546\u673a":"\u65b0\u589e\u5546\u673a"}</h3><select id="ot" class="field"><option>\u7ef4\u4fdd</option><option>\u8017\u6750</option><option>\u8bbe\u5907\u9500\u552e</option></select><input id="on" class="field" placeholder="\u9879\u76ee\u540d\u79f0" value="${esc(o.name)}"><input id="oh" class="field" placeholder="\u533b\u9662" value="${esc(o.hospital)}"><input id="od" class="field" placeholder="\u79d1\u5ba4" value="${esc(o.department)}"><input id="oc" class="field" placeholder="\u8054\u7cfb\u4eba" value="${esc(o.contact)}"><input id="os" class="field" placeholder="\u9636\u6bb5" value="${esc(o.stage)}"><input id="oa" class="field" placeholder="\u9884\u8ba1\u91d1\u989d" value="${esc(o.amount)}"><input id="oe" class="field" type="date" value="${esc(o.expectedDate)}"><input id="ox" class="field" placeholder="\u4e0b\u4e00\u6b65" value="${esc(o.next)}"><div class="modal-row"><button class="btn tertiary" onclick="closeModal()">\u53d6\u6d88</button><button class="btn" onclick="saveOpportunity('${esc(id||"")}')">\u4fdd\u5b58</button></div></section></div>`;render();document.getElementById("ot").value=o.type}
function saveOpportunity(id){const o={id:id||`o-${Date.now()}`,type:document.getElementById("ot").value,name:document.getElementById("on").value.trim(),hospital:document.getElementById("oh").value.trim(),department:document.getElementById("od").value.trim(),contact:document.getElementById("oc").value.trim(),stage:document.getElementById("os").value.trim(),amount:document.getElementById("oa").value.trim(),expectedDate:document.getElementById("oe").value,next:document.getElementById("ox").value.trim()};if(!o.name)return;const i=state.opportunities.findIndex(x=>x.id===o.id);if(i>=0)state.opportunities[i]=o;else state.opportunities.unshift(o);save();modal="";render()}
function settingsView(){return `<section class="card"><h2>AI \u8bbe\u7f6e</h2><input id="endpoint" class="field" placeholder="Cloudflare Worker URL" value="${esc(state.ai.endpoint||"")}"><button class="btn block" onclick="saveSettings()">\u4fdd\u5b58</button><button class="btn secondary block" onclick="testAI()">\u6d4b\u8bd5\u8fde\u63a5</button><div id="msg" class="small"></div></section>`}
function saveSettings(){state.ai.endpoint=document.getElementById("endpoint").value.trim();save();document.getElementById("msg").textContent="\u5df2\u4fdd\u5b58"}
async function testAI(){saveSettings();try{const r=await fetch(`${state.ai.endpoint.replace(/\/$/,"")}/api/ping`);document.getElementById("msg").textContent=r.ok?"\u8fde\u63a5\u6210\u529f":"\u8fde\u63a5\u5931\u8d25"}catch{document.getElementById("msg").textContent="\u8fde\u63a5\u5931\u8d25"}}
function reviewDate(){return addDays(today(),-7)}
function followupReview(){const completed=[...state.tasks,...state.followups,...state.radar].filter(x=>x.done&&x.completedAt&&x.completedAt>=reviewDate());const stale=state.hospitals.filter(x=>x.contact&&(!x.lastContact||x.lastContact<=addDays(today(),-30)));const soon=state.opportunities.filter(x=>x.expectedDate&&x.expectedDate>=today()&&x.expectedDate<=addDays(today(),30));return `<section class="card"><h3>鏈懆澶嶇洏</h3><div class="followup-stats"><span class="tag green">鏈懆宸插畬鎴?${completed.length}</span><span class="tag red">寰呰仈绯?${stale.length}</span><span class="tag gold">30澶╁唴鍟嗘満 ${soon.length}</span></div>${stale.length?`<div class="small">寤鸿浼樺厛鑱旂郴锛?{stale.map(x=>esc(x.name)).join("銆?)}</div>`:"<div class=\"small\">鏆傛棤瓒呰繃30澶╂湭鑱旂郴鐨勮仈绯讳汉</div>"}${soon.length?`<div class="small">涓磋繎鍟嗘満锛?{soon.map(x=>esc(x.name)).join("銆?)}</div>`:""}</section>`}
function radarView(){const items=state.radar.filter(x=>!x.done).sort(radarOrder);const overdue=items.filter(x=>radarStatus(x)==="overdue");const todayItems=items.filter(x=>radarStatus(x)==="today");const upcoming=items.filter(x=>radarStatus(x)==="upcoming");return `${followupReview()}<section class="card"><h2>鏅鸿兘璺熻繘涓績</h2><p class="muted">鎸夋棩鏈熸鏌ュ尰闄€佽仈绯讳汉銆佸晢鏈哄拰涓嬩竴姝ャ€傚凡瀹屾垚浜嬮」浼氳嚜鍔ㄧ寮€閲嶇偣銆?/p><div class="followup-stats"><span class="tag red">宸查€炬湡 ${overdue.length}</span><span class="tag gold">浠婂ぉ ${todayItems.length}</span><span class="tag">鏈潵鑺傜偣 ${upcoming.length}</span></div>${radarSection("宸查€炬湡",overdue)}${radarSection("浠婂ぉ璇ュ仛",todayItems)}${radarSection("鏈潵鑺傜偣",upcoming)}${items.length?"":"<div class=\"empty\">鏈潵闆疯揪杩樻槸绌虹殑</div>"}</section>`}
function todayPlanCandidates(){const currentDate=today();const radarCandidates=state.radar.filter(item=>!item.done&&((item.dueDate||item.date||"9999-12-31")<=currentDate));const staleContacts=state.hospitals.filter(hospital=>hospital.contact&&(!hospital.lastContact||hospital.lastContact<=addDays(currentDate,-30))).map(hospital=>({title:"联系"+hospital.contact+"跟进最新进展",what:"联系"+hospital.name+"的"+hospital.contact+"，确认当前项目或采购进度",why:"超过30天未联系，今天先恢复沟通。",dueDate:currentDate,priority:"high",hospital:hospital.name,department:hospital.department,contact:hospital.contact,source:"followup"}));const nearOpportunities=state.opportunities.filter(opportunity=>opportunity.expectedDate&&opportunity.expectedDate>=currentDate&&opportunity.expectedDate<=addDays(currentDate,7)).map(opportunity=>({title:"推进"+opportunity.name+"下一步",what:opportunity.next||("联系"+(opportunity.contact||"相关联系人")+"确认"+opportunity.name+"进展"),why:"商机已进入7天节点窗口，今天确认下一步更稳妥。",dueDate:currentDate,priority:"high",hospital:opportunity.hospital,department:opportunity.department,contact:opportunity.contact,project:opportunity.name,source:"followup"}));return [...radarCandidates,...staleContacts,...nearOpportunities].filter((item,index,list)=>list.findIndex(candidate=>fp(candidate)===fp(item))===index)}
function createTodayPlan(){const candidates=todayPlanCandidates();let added=0;for(const candidate of candidates){if(!anyTask(candidate)){state.tasks.unshift({...candidate,id:"plan-"+Date.now()+"-"+added,text:candidate.what,createdAt:today(),done:false});added++}}save();feedback.plan=added?"已生成"+added+"件今日推进任务":"今日推进任务已存在，无需重复添加";render()}
function followupPlan(){const candidates=todayPlanCandidates();const todayCount=state.tasks.filter(item=>!item.done&&item.dueDate===today()).length;return "<section class=\"card\"><div class=\"row\"><div><h3>今日推进计划</h3><div class=\"small\">把逾期雷达、久未联系客户和临近商机统一整理成今天要做的事。</div></div><button class=\"btn\" onclick=\"createTodayPlan()\">一键生成今日计划</button></div><div class=\"followup-stats\"><span class=\"tag red\">建议推进 "+candidates.length+"</span><span class=\"tag gold\">今日任务 "+todayCount+"</span></div>"+(feedback.plan?"<div class=\"feedback\">✓ "+esc(feedback.plan)+"</div>":"")+"</section>"}
function radarView(){const items=state.radar.filter(x=>!x.done).sort(radarOrder);const overdue=items.filter(x=>radarStatus(x)==="overdue");const todayItems=items.filter(x=>radarStatus(x)==="today");const upcoming=items.filter(x=>radarStatus(x)==="upcoming");return followupReview()+followupPlan()+"<section class=\"card\"><h2>智能跟进中心</h2><p class=\"muted\">按日期检查医院、联系人、商机和下一步。已完成事项会自动离开重点。</p><div class=\"followup-stats\"><span class=\"tag red\">已逾期 "+overdue.length+"</span><span class=\"tag gold\">今天 "+todayItems.length+"</span><span class=\"tag\">未来节点 "+upcoming.length+"</span></div>"+radarSection("已逾期",overdue)+radarSection("今天该做",todayItems)+radarSection("未来节点",upcoming)+(items.length?"":"<div class=\"empty\">未来雷达还是空的</div>")+"</section>"}
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js?v=066").catch(()=>{});
render();

if(!Array.isArray(state.inbox))state.inbox=[];
function learningTip(){const tips=["提示：把 AI 当成执行伙伴，提问时补充目标、截止时间和限制条件。","提示：让 AI 先给结构化清单，再让它解释原因，结果会更容易执行。","提示：重要信息先进入收件箱，确认后再写入客户、任务或健康记录。","提示：让 AI 复盘时同时问‘下一步是什么’和‘如果不做会怎样’。","提示：涉及隐私的照片和文件先确认用途，不要把身份证、银行卡等敏感资料上传。"];return tips[new Date().getDate()%tips.length]}
function inboxPanel(){return `<section class="card"><div class="row"><div><h3>AI收件箱</h3><div class="small">照片、文件和随手问题先归集在这里，确认后再进入对应分区。</div></div><span class="tag">${state.inbox.length} 条</span></div>${state.inbox.slice(0,5).map(item=>`<div class="list-item"><strong>${esc(item.name)}</strong><div class="small">${esc(item.category||"待整理")} · ${esc(item.createdAt||"")}</div><div class="small">${esc(item.summary||"等待 AI 整理")}</div></div>`).join("")||'<div class="empty">收件箱还是空的</div>'}</section>`}
function readCapture(file){return new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>resolve("");if(file.type.startsWith("image/")&&file.size<=2*1024*1024)reader.readAsDataURL(file);else if(file.type.startsWith("text/")||/json|csv|markdown/.test(file.type)||/\.(txt|md|csv|json)$/i.test(file.name))reader.readAsText(file);else resolve("")})}
async function captureFiles(){const input=document.getElementById("captureFiles");const note=document.getElementById("note")?.value.trim()||"";if(!input?.files?.length&&!note)return;const files=Array.from(input?.files||[]);const attachments=[];for(const file of files){const content=await readCapture(file);attachments.push({name:file.name,type:file.type||"application/octet-stream",size:file.size,content})}const endpointRaw=state.ai.endpoint||"";let result=null;if(endpointRaw){try{const response=await fetch(endpointRaw.replace(/\/$/,"")+"/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"capture_analyze",message:note,attachments,context:{today:today(),hospitals:state.hospitals,opportunities:state.opportunities}})});if(response.ok)result=await response.json()}catch{}}for(const file of attachments){const match=result?.files?.find(item=>item.name===file.name);state.inbox.unshift({id:"inbox-"+Date.now()+Math.random(),name:file.name,type:file.type,size:file.size,createdAt:today(),category:match?.category||"待整理",summary:match?.summary||"文件已归集，等待进一步整理",tags:match?.tags||[],source:"capture"})}if(!files.length)state.inbox.unshift({id:"inbox-"+Date.now(),name:"随手问题",type:"text/plain",createdAt:today(),category:result?.category||"AI问题",summary:result?.summary||note,source:"capture"});save();feedback.capture="已归集到 AI 收件箱";render()}
function assistantView(){return `<section class="card"><h2>AI个人助理</h2><p class="muted">问题、随口记、照片和文件都可以先扔进来，AI 会帮助你归类、提炼和安排下一步。</p><textarea id="note" class="field" rows="5" placeholder="例如：北医三院现在有哪些事？"></textarea><input id="captureFiles" class="field" type="file" multiple accept="image/*,.txt,.md,.csv,.json,.pdf,.doc,.docx"><div class="small">支持照片和常见文件归集；敏感资料请先确认是否需要上传。</div><div class="quick-queries"><button class="btn tertiary" onclick="fillQuery('北医三院现在有哪些事？')">查医院进展</button><button class="btn tertiary" onclick="fillQuery('今天先做什么？')">今天先做什么</button><button class="btn tertiary" onclick="fillQuery('本周重点是什么？')">本周重点</button></div><button class="btn block" onclick="askAI()">提问 / 拆解任务</button><button class="btn secondary block" onclick="captureFiles()">上传并归集</button>${feedback.capture?`<div class="feedback">✓ ${esc(feedback.capture)}</div>`:""}${answerText?`<section class="answer-card"><h3>AI回答</h3><div>${esc(answerText).replace(/\n/g,"<br>")}</div></section>`:""}${actions.map(actionCard).join("")}<section class="card"><h3>今日 AI 小课堂</h3><div class="small">${learningTip()}</div></section></section>${inboxPanel()}`}
render();


