WORKBENCH_LATEST_VERSION="1.5.0";
WORKBENCH_STABLE_QUERY="1500925";

function workbenchProjectsV150(){return contractProjectsV138().concat(businessProjectsV140())}
function workbenchActionV150(project){return contractActionV139(project)||{}}
function workbenchSectionV150(title,items,empty){return '<section class="card"><h2>'+title+'</h2>'+(items.length?items.map(function(item){var project=item.project,action=item.action;return '<button class="workbench-project-v150" onclick="contractOpenDetailV139(&quot;'+esc(project.id)+'&quot;)"><strong>'+esc(project.name)+'</strong><span>'+esc(project.hospital)+' · '+esc(action.currentStatus||'未标记')+(action.followupDate?' · '+esc(action.followupDate):'')+'</span>'+(action.nextAction?'<small>下一步：'+esc(action.nextAction)+'</small>':'')+'</button>'}).join(''):'<p class="muted">'+empty+'</p>')+'</section>'}
function workbenchHomeV150(){
  var projects=workbenchProjectsV150().map(function(project){return {project:project,action:workbenchActionV150(project)}});
  var due=addDays(today(),7);
  var mine=projects.filter(function(item){return /要我行动/.test(item.action.currentStatus||'')});
  var waiting=projects.filter(function(item){return /等待别人|等医院|等厂家|等同事|等第三方/.test(item.action.currentStatus||'')});
  var upcoming=projects.filter(function(item){return item.action.followupDate>=today()&&item.action.followupDate<=due&&!mine.includes(item)});
  var inbox=Array.isArray(state.inbox)?state.inbox.filter(function(item){return !/已确认|已整理成册|已忽略/.test(item.status||'')}):[];
  var money=projects.filter(function(item){return /资金异常|需催款|开票待办/.test(item.action.currentStatus||'')});
  return '<section class="card"><h2>快速记录</h2><div class="workbench-quick-v150"><button class="btn" onclick="go(\'capture\')">随口记</button><button class="btn secondary" onclick="go(\'capture\');openCaptureV150(\'photo\')">拍照</button><button class="btn secondary" onclick="go(\'capture\');openCaptureV150(\'file\')">上传文件</button></div></section>'+workbenchSectionV150('今天要我行动 · '+mine.length,mine,'目前没有明确标为“要我行动”的项目。')+workbenchSectionV150('等待中 · '+waiting.length,waiting.slice(0,5),'目前没有等待别人回复的项目。')+workbenchSectionV150('未来7天 · '+upcoming.length,upcoming,'未来7天没有明确的跟进日期。')+'<section class="card"><div class="row"><h2>收件箱 · '+inbox.length+'</h2><button class="btn secondary" onclick="go(\'capture\')">去整理</button></div><p class="muted">只展示尚未整理的记录和文件。</p></section>'+workbenchSectionV150('资金异常 · '+money.length,money,'没有人工标记需要处理的资金异常；未收款不会自动成为待办。');
}
function workbenchCaptureV150(){return '<section class="card"><h2>先记下来</h2><p class="muted">记录先进入收件箱，不会自动新建项目或任务。</p><textarea id="quick-note-v150" class="field" rows="4" placeholder="随时记一件事"></textarea><button class="btn block" onclick="saveQuickNoteV150()">存入收件箱</button><div class="workbench-quick-v150"><button class="btn secondary" onclick="openCaptureV150(\'photo\')">拍照</button><button class="btn secondary" onclick="openCaptureV150(\'file\')">上传文件</button></div><input id="captureFiles" type="file" multiple accept="image/*,.txt,.md,.csv,.json,.pdf,.doc,.docx,.xlsx,.xls" style="position:absolute;width:1px;height:1px;opacity:0" onchange="captureFiles()"><p id="capture-message-v150" role="status" class="muted"></p></section>'+inboxPanel()}
function openCaptureV150(kind){var input=document.getElementById('captureFiles');if(!input)return;input.accept=kind==='photo'?'image/*':'image/*,.txt,.md,.csv,.json,.pdf,.doc,.docx,.xlsx,.xls';input.multiple=kind!=='photo';if(kind==='photo')input.setAttribute('capture','environment');else input.removeAttribute('capture');input.click()}
function saveQuickNoteV150(){var input=document.getElementById('quick-note-v150'),value=input&&input.value.trim();if(!value)return;var before=state.inbox;state.inbox=Array.isArray(before)?before.slice():[];state.inbox.unshift({id:'note-'+Date.now(),name:'随口记 · '+today(),createdAt:today(),category:'待整理',summary:value.slice(0,180),textContent:value,contentAvailable:true,status:'待选择',source:'quick-note'});try{save();render()}catch(error){state.inbox=before;var message=document.getElementById('capture-message-v150');if(message)message.textContent='保存失败，请检查本机存储空间。'}}
function workbenchMoreV150(){return '<section class="card"><h2>更多</h2><div class="workbench-menu-v150"><button onclick="go(\'capture\')">收件箱与文件</button><button onclick="go(\'life-v150\')">生活记录</button><button onclick="go(\'assistant\')">AI辅助</button><button onclick="go(\'tasks\')">原有任务</button><button onclick="go(\'radar\')">原有未来记录</button><button onclick="go(\'business-import\')">导入业务项目</button><button onclick="go(\'contracts\')">导入合同底表</button><button onclick="go(\'settings\')">备份、恢复与隐私设置</button></div><p class="muted">旧数据和原页面仍保留，仅退出主导航。</p></section>'}
function workbenchLifeV150(){var items=Array.isArray(state.life)?state.life:[];return '<section class="card"><button class="btn secondary" onclick="go(\'more\')">← 返回更多</button><h2>生活记录</h2><p class="muted">原有生活数据保留，新的随口记先进入收件箱。</p>'+(items.length?items.slice(0,50).map(function(item){return '<div class="list-item"><strong>'+esc(item.title||item.name||item.text||'生活记录')+'</strong><p class="muted">'+esc(item.content||item.note||item.date||'')+'</p></div>'}).join(''):'<p class="muted">暂无生活记录。</p>')+'</section>'}
const workbenchPageViewBaseV150=pageView;
pageView=function(){if(page==='home')return workbenchHomeV150();if(page==='capture')return workbenchCaptureV150();if(page==='more')return workbenchMoreV150();if(page==='life-v150')return workbenchLifeV150();if(page==='work')return customersView();return workbenchPageViewBaseV150()};
render=function(){
  var current=page==='customers'||page==='hospital-detail'||page==='business-form'||page==='business-import'||page==='contract-detail'?'work':page;
  var links=[['home','首页'],['work','工作'],['capture','＋'],['contracts','合同/资金'],['more','更多']];
  document.getElementById('app').innerHTML='<div class="shell"><header class="top"><h1>我的工作台</h1><p>V1.5.0 · 精简定型版</p></header><main class="content">'+pageView()+'</main><nav class="nav workbench-nav-v150" aria-label="主导航">'+links.map(function(link){return '<button type="button" data-route="'+link[0]+'" class="'+(current===link[0]?'active':'')+'">'+link[1]+'</button>'}).join('')+'</nav></div>'+modal;
  if(page==='contracts')contractRenderGroupsV138();
};
document.addEventListener('click',function(event){var button=event.target.closest&&event.target.closest('.workbench-nav-v150 button[data-route]');if(!button)return;event.preventDefault();go(button.dataset.route)},true);
var workbenchStylesV150=document.createElement('style');workbenchStylesV150.textContent='.workbench-nav-v150{z-index:100;pointer-events:auto;justify-content:space-around}.workbench-nav-v150 button{pointer-events:auto;min-height:44px;min-width:54px;font-size:13px}.workbench-nav-v150 button[data-route="capture"]{background:#1976d2;color:#fff;font-size:21px;line-height:1}.workbench-quick-v150{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.workbench-quick-v150 .btn{flex:1;min-width:90px}.workbench-project-v150{display:block;width:100%;padding:12px 4px;text-align:left;background:none;border:0;border-top:1px solid #d9e2ec;color:#102a43}.workbench-project-v150 strong,.workbench-project-v150 span,.workbench-project-v150 small{display:block}.workbench-project-v150 span,.workbench-project-v150 small{color:#627d98}.workbench-menu-v150{display:grid;gap:8px}.workbench-menu-v150 button{padding:13px;text-align:left;border:1px solid #d9e2ec;background:#f6f9fc;border-radius:10px;color:#102a43}';document.head.appendChild(workbenchStylesV150);
render();

