const KEY="personalWorkbench";
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(date,days)=>{const d=new Date(date+"T12:00:00");d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const cleanText=value=>String(value||"").replace(/```[\s\S]*?```/g,"").replace(/^[\s#>*`_-]+/gm,"").replace(/\*\*/g,"").replace(/\r/g,"").trim();
const defaultState=()=>({notes:[],finance:[],life:[],health:[],study:[],tasks:[],followups:[],radar:[],ai:{endpoint:"",auto:false},passkey:{enabled:false},backupVersion:1});
let state=(()=>{try{return {...defaultState(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return defaultState()}})();
let page="home", actions=[], feedback={};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function render(){document.getElementById("app").innerHTML=`<div class="shell"><header class="top"><h1>个人工作台</h1><p>V0.5.4 · 行动卡精修版</p></header><main class="content">${pageView()}</main><nav class="nav">${[["home","首页"],["assistant","AI助理"],["tasks","执行"],["radar","未来雷达"],["settings","设置"]].map(([id,label])=>`<button class="${page===id?'active':''}" onclick="go('${id}')">${label}</button>`).join("")}</nav></div>${modal||""}`}
function go(next){page=next;modal="";render()}
let modal="";
function pageView(){if(page==="assistant")return assistantView();if(page==="tasks")return tasksView();if(page==="radar")return radarView();if(page==="settings")return settingsView();return homeView()}
function homeView(){const pending=state.tasks.filter(x=>!x.done).length;return `<section class="card"><div class="row"><div><div class="small">今天</div><div class="metric">${pending}</div><div>件待执行</div></div><button class="btn" onclick="go('assistant')">记录一件事</button></div></section><section class="card"><h2>工作台分区</h2><div class="tabs">${["随口记","财务","生活","健康","备考"].map(x=>`<span class="tag">${x}</span>`).join("")}</div><p class="muted">你的原有记录、AI设置、Face ID/Passkey和备份数据继续保存在本机。AI建议可一键进入执行或未来雷达。</p></section><section class="card"><h2>最近行动</h2>${state.tasks.slice(0,3).map(x=>`<div class="list-item"><div class="row"><b>${escapeHtml(x.text)}</b><span class="tag ${x.done?'green':''}">${x.done?'已完成':'待执行'}</span></div></div>`).join("")||'<div class="empty">还没有行动，去 AI 助理记录一件事。</div>'}</section>`}
function assistantView(){return `<section class="card"><h2>AI个人助理</h2><p class="muted">输入随口记录，AI会整理成最多3张短行动卡。默认只看三段执行信息，详细分析按需展开。</p><textarea id="note" rows="4" class="field" placeholder="例如：主任说下个月增加光纤采购量，我现在下一步应该做什么？"></textarea><button class="btn block" onclick="askAI()">生成行动建议</button><div id="aiResult">${actions.length?actions.map(actionCard).join(""):''}</div></section><section class="card"><h3>本地兼容区</h3><div class="tabs">${["随口记","财务","生活","健康","备考","Face ID / Passkey","备份"].map(x=>`<span class="tag">${x}</span>`).join("")}</div><p class="small">本版继续使用同一个本地存储容器，不清理原有数据。</p></section>`}
function actionCard(action,index){const id=action.id||index;return `<article class="card action-card"><div class="row"><span class="tag">行动 ${index+1}</span><span class="small">可直接执行</span></div><h3>${escapeHtml(action.title)}</h3><div class="action-line"><b>要做什么</b><span>${escapeHtml(action.what)}</span></div><div class="action-line"><b>为什么现在做</b><span>${escapeHtml(action.why)}</span></div><div class="action-line"><b>建议话术</b><span>${escapeHtml(action.script||'我想先确认一下当前需求、数量和时间节点，方便我安排下一步。')}</span></div><details><summary>查看详细分析</summary><p class="small">${escapeHtml(action.detail||'这项行动用于把信息变成明确的负责人、时间点和下一步交付物。')}</p></details><div class="actions"><button class="btn" onclick="addTask(${id})">加入今日任务</button><button class="btn secondary" onclick="openDateModal(${id},'follow')">设为本周跟进</button><button class="btn tertiary" onclick="openDateModal(${id},'radar')">加入未来雷达</button></div>${feedback[id]?`<div class="feedback">✓ ${escapeHtml(feedback[id])}</div>`:''}</article>`}
function fallbackActions(note){const text=cleanText(note).replace(/^\d+[.)、]\s*/,"");return [{title:"先把这件事变成一个明确动作",what:`确认“${text.slice(0,42)}${text.length>42?'…':''}”的具体需求、数量和时间`,why:"现在先确认关键事实，后续安排才不会反复修改。",script:"我先确认一下具体需求、数量和时间节点，确认后我马上给你反馈。",detail:"先锁定对象、数量、时间和负责人，再决定采购、沟通或执行路径。"},{title:"找到对应负责人并确认路径",what:"联系相关负责人，确认流程、预算和下一步节点",why:"尽早找到流程入口，可以减少等待和信息遗漏。",script:"这件事我来跟进流程，想和你确认一下负责人与预计完成时间。",detail:"把事项拆成负责人、流程入口、所需材料和预计完成时间。"},{title:"设一个回看节点",what:"在关键节点前回看进度，并主动同步结果",why:"有明确回看时间，事情才不容易停在口头沟通。",script:"我会在节点前再跟进一次，届时把进度和需要你确认的地方一起发来。",detail:"为事项设置一个可调整的日期，按结果继续推进或改计划。"}]}
async function askAI(){const input=document.getElementById("note");const note=input?.value.trim();if(!note)return;actions=fallbackActions(note);const endpoint=(state.ai.endpoint||"").replace(/\/$/,"");if(endpoint){try{const response=await fetch(endpoint+"/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:note,context:{tasks:state.tasks,followups:state.followups,radar:state.radar}})});if(response.ok){const data=await response.json();const parsed=normalizeAI(data);if(parsed.length)actions=parsed}}catch{}}render()}
function normalizeAI(data){const raw=data.actions||data.suggestions||data.items; if(!Array.isArray(raw))return[];return raw.slice(0,3).map((x,i)=>{if(typeof x==='string')return {title:x.replace(/^\d+[.)、]\s*/,""),what:x,why:"这项行动能把当前信息推进到下一步。",script:"我先确认一下具体需求和时间节点。",detail:x};return {title:cleanText(x.title||x.name||`行动 ${i+1}`).replace(/^\d+[.)、]\s*/,""),what:cleanText(x.what||x.action||x.next||x.title),why:cleanText(x.why||x.reason||"现在处理可以尽早锁定关键事实。"),script:cleanText(x.script||x.words||x.talk),detail:cleanText(x.detail||x.analysis||x.explain)}})}
function addTask(id){const action=actions[id];if(!action)return;state.tasks.unshift({id:"task-"+Date.now(),text:action.what,title:action.title,source:"ai",createdAt:today(),done:false});save();feedback[id]="已加入今日任务";render()}
function openDateModal(id,type){const action=actions[id];if(!action)return;const defaultDate=type==='follow'?plusDays(today(),Math.max(1,7-new Date().getDay())):plusDays(today(),30);modal=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><section class="modal"><h3>${type==='follow'?'设为本周跟进':'加入未来雷达'}</h3><p class="muted">${escapeHtml(action.what)}</p><label class="small">${type==='follow'?'跟进日期':'提醒日期'}</label><input id="dateValue" type="date" value="${defaultDate}" min="${today()}"><div class="modal-row"><button class="btn tertiary" onclick="closeModal()">取消</button><button class="btn" onclick="saveDateAction(${id},'${type}')">确认保存</button></div></section></div>`;render()}
function saveDateAction(id,type){const date=document.getElementById("dateValue")?.value;if(!date)return;const action=actions[id];const row={id:(type==='follow'?'follow-':'radar-')+Date.now(),text:action.what,title:action.title,date,source:"ai",createdAt:today()};if(type==='follow')state.followups.unshift(row);else state.radar.unshift(row);save();feedback[id]=type==='follow'?`已设为本周跟进：${date}`:`已加入未来雷达：${date}`;modal="";render()}
function closeModal(){modal="";render()}
function tasksView(){return `<section class="card"><h2>今日任务</h2>${state.tasks.map(x=>`<div class="list-item"><div class="row"><label><input type="checkbox" ${x.done?'checked':''} onchange="toggleTask('${x.id}')"> ${escapeHtml(x.title||x.text)}</label><span class="tag">${escapeHtml(x.text)}</span></div></div>`).join("")||'<div class="empty">暂无今日任务</div>'}</section><section class="card"><h2>本周跟进</h2>${state.followups.map(x=>`<div class="list-item"><div class="row"><b>${escapeHtml(x.title)}</b><span class="tag">${x.date}</span></div><div class="small">${escapeHtml(x.text)}</div></div>`).join("")||'<div class="empty">暂无跟进</div>'}</section>`}
function toggleTask(id){const item=state.tasks.find(x=>x.id===id);if(item)item.done=!item.done;save();render()}
function radarView(){return `<section class="card"><h2>未来雷达</h2><p class="muted">按日期保存需要之后再回看的事项。</p>${state.radar.map(x=>`<div class="list-item"><div class="row"><b>${escapeHtml(x.title)}</b><span class="tag">${x.date}</span></div><div class="small">${escapeHtml(x.text)}</div></div>`).join("")||'<div class="empty">未来雷达还是空的</div>'}</section>`}
function settingsView(){return `<section class="card"><h2>AI设置</h2><label class="small">Cloudflare Worker 地址</label><input id="endpoint" class="field" value="${escapeHtml(state.ai.endpoint)}" placeholder="https://你的-worker.workers.dev"><label class="small"><input id="auto" type="checkbox" ${state.ai.auto?'checked':''}> 随口记入库后自动生成下一步建议</label><button class="btn block" onclick="saveSettings()">保存 AI 设置</button><button class="btn secondary block" onclick="testAI()">测试连接</button><div id="settingMessage" class="small"></div></section><section class="card"><h2>数据与设备</h2><p class="muted">Face ID / Passkey：${state.passkey.enabled?'已启用':'按原有设置使用'}。本版本不改动认证流程。</p><button class="btn tertiary" onclick="exportBackup()">导出本地备份</button><input type="file" accept="application/json" onchange="importBackup(event)" class="field" style="margin-top:9px"></section>`}
function saveSettings(){state.ai.endpoint=document.getElementById("endpoint").value.trim();state.ai.auto=document.getElementById("auto").checked;save();document.getElementById("settingMessage").textContent="AI 设置已保存到本机。"}
async function testAI(){saveSettings();const box=document.getElementById("settingMessage");if(!state.ai.endpoint){box.textContent="请先填写 Worker 地址。";return}box.textContent="正在测试连接…";try{const response=await fetch(state.ai.endpoint.replace(/\/$/,"")+"/api/ping");const data=await response.json().catch(()=>({}));box.textContent=response.ok?`连接成功：${data.model||'gpt-5.5'}`:"连接失败，请检查地址。"}catch{box.textContent="连接失败，请检查 Worker 地址或网络。"}}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`个人工作台备份-${today()}.json`;link.click();URL.revokeObjectURL(link.href)}
function importBackup(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const incoming=JSON.parse(reader.result);state={...defaultState(),...incoming};save();render()}catch{alert("备份文件格式不正确")}};reader.readAsText(file)}
render();
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js?v=054").catch(()=>{});
